#!/usr/bin/env node
/**
 * check-tokens.mjs — enforces the theming constraint.
 *
 * The whole point of this site's CSS is that tokens.css is the only place
 * literal design values live, so the theme can be swapped by editing that one
 * file. That's easy to state and easy to erode. This script makes it a build
 * failure instead of a code-review habit.
 *
 * Run: pnpm run lint:tokens   (also part of `pnpm run verify`)
 *
 * Scans every .astro/.css file EXCEPT src/styles/tokens.css for:
 *   - literal colors        #abc, #aabbcc, rgb(), rgba(), hsl(), hwb(), lab()
 *   - px font-sizes         font-size: 14px
 *   - font-family stacks    font-family: Helvetica, sans-serif
 *
 * Deliberately NOT flagged:
 *   - `currentColor`, `transparent`, `inherit` — theme-independent keywords.
 *   - px in radii/borders/shadow offsets — hairline and geometry values that
 *     shouldn't scale with the user's font size. Colors and type are the
 *     things that must stay swappable.
 *   - color-mix(...) over var(--…) — composes tokens, introduces no literal.
 */

import { readdir, readFile } from 'node:fs/promises';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SCAN_DIRS = ['src'];
const EXTENSIONS = ['.astro', '.css'];

/** The one file allowed to contain literals. */
const ALLOWLIST = new Set(['src/styles/tokens.css']);

const RULES = [
  {
    id: 'literal-color',
    // Hex, or any of the functional color notations.
    pattern: /#[0-9a-fA-F]{3,8}\b|\b(?:rgba?|hsla?|hwb|lab|lch|oklab|oklch)\s*\(/g,
    message: 'literal color — add a token in tokens.css and use var(--…)',
  },
  {
    id: 'px-font-size',
    pattern: /font-size\s*:\s*[^;{}]*\b\d*\.?\d+px/g,
    message: 'px font-size — use a --text-* token (rem-based, respects user zoom)',
  },
  {
    id: 'hardcoded-font-family',
    // Any font-family whose value isn't purely var()/inherit/keyword-driven.
    pattern: /font-family\s*:\s*(?![^;{}]*var\(--)[^;{}]*(?:[a-zA-Z]{2,}|"|')[^;{}]*/g,
    message: 'hardcoded font stack — use var(--font-sans) or var(--font-mono)',
  },
];

/** Ignore these — they're theme-independent or reference a token already. */
const EXEMPT_LINE = [
  /--shiki-/, // generated by Shiki; documented exception in global.css
  /font-family\s*:\s*inherit/,
  /font-family\s*:\s*var\(--/,
];

async function* walk(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue;
      yield* walk(path);
    } else if (EXTENSIONS.some((ext) => entry.name.endsWith(ext))) {
      yield path;
    }
  }
}

/** Strip comments so documentation examples don't trip the rules. */
function stripComments(source) {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, (match) => match.replace(/[^\n]/g, ' '))
    .replace(/(^|[^:])\/\/[^\n]*/g, (match) => match.replace(/[^\n]/g, ' '));
}

const violations = [];

for (const dir of SCAN_DIRS) {
  for await (const file of walk(join(ROOT, dir))) {
    const rel = relative(ROOT, file).split('\\').join('/');
    if (ALLOWLIST.has(rel)) continue;

    const lines = stripComments(await readFile(file, 'utf8')).split('\n');

    lines.forEach((line, index) => {
      if (EXEMPT_LINE.some((exempt) => exempt.test(line))) return;

      for (const rule of RULES) {
        rule.pattern.lastIndex = 0;
        const match = rule.pattern.exec(line);
        if (match) {
          violations.push({
            file: rel,
            line: index + 1,
            rule: rule.id,
            message: rule.message,
            snippet: line.trim().slice(0, 96),
          });
        }
      }
    });
  }
}

if (violations.length === 0) {
  console.log('✓ tokens: no literal colors, px font-sizes, or font stacks outside tokens.css');
  process.exit(0);
}

console.error(`\n✗ tokens: ${violations.length} violation(s)\n`);
for (const v of violations) {
  console.error(`  ${v.file}:${v.line}  [${v.rule}]`);
  console.error(`    ${v.snippet}`);
  console.error(`    → ${v.message}\n`);
}
console.error('These values belong in src/styles/tokens.css so the theme stays swappable.\n');
process.exit(1);
